### ISSUE TITLE
Creating interaction function with API (Goodreads) 

### ISSUE THREAD

**Issue by Adogeon** [valeriaszy/Project-One#8]
## Acceptance Criteria:
- [ ] Received response from the API
- [ ] Parsing the required information from the API
- [ ] Picture of the movie, books, comic
- [ ] Summary
- [ ] Tittle
- [ ] Rating
- [ ] Creator (Author, Artist, Directors, Actors)

**Comment by isinselen** [comment]
We'll use Google book API due to CORS issue
